name: CI-CD Pipeline

on:
  # CI Auto Trigger
  push:
    branches:
      - hager/task1

  # CD Manual Trigger
  workflow_dispatch:
    inputs:
      deploy_target:
        description: "Choose deployment target"
        required: true
        type: choice
        options:
          - local
          - ec2


jobs:

# =========================
# BUILD JOB
# =========================
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t myapp:ci .

      - name: Save Image As Artifact
        run: |
          docker save myapp:ci -o myapp-image.tar

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: myapp-image.tar


# =========================
# SCAN JOB
# =========================
  scan:
    name: Trivy Scan
    needs: build
    runs-on: ubuntu-latest

    steps:

      - name: Download Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Image
        run: |
          docker load -i myapp-image.tar

      # Download HTML Template
      - name: Download Trivy HTML Template
        run: |
          wget https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl

      - name: Trivy Scan (HTML Report)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: myapp:ci
          format: template
          template: "html.tpl"
          output: report.html
          exit-code: 0

      - name: Prepare Scan Artifact
        run: |
          mkdir scan-dir
          cp report.html scan-dir/

      - name: Upload Scan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: scan-dir
          path: scan-dir/


# =========================
# PUSH JOB
# =========================
  push:
    name: Push Image To DockerHub
    needs: scan
    runs-on: ubuntu-latest

    steps:

      - name: Download Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Image
        run: |
          docker load -i myapp-image.tar

      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Tag Image
        run: |
          docker tag myapp:ci ${{ secrets.DOCKER_USER }}/myapp:ci

      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKER_USER }}/myapp:ci


# =========================
# CD JOB (CONDITIONAL)
# =========================
  cd:
    name: Deploy Job
    needs: push
    runs-on: ubuntu-latest

    steps:

      # -------- LOCAL DEPLOY --------
      - name: Deploy To Local
        if: github.event.inputs.deploy_target == 'local'
        run: |
          echo "Deploying to LOCAL..."
          docker pull ${{ secrets.DOCKER_USER }}/myapp:ci
          docker stop myapp || true
          docker rm myapp || true
          docker run -d --name myapp -p 8080:80 ${{ secrets.DOCKER_USER }}/myapp:ci


      # -------- EC2 DEPLOY --------
      - name: Deploy To EC2
        if: github.event.inputs.deploy_target == 'ec2'
        run: |
          echo "Deploying to EC2..."
          echo "Later we will add SSH + docker pull/run here"
