name: CI Pipeline

on:
  push:
    branches:
      - hager-ci

jobs:

  build_scan:
    name: Build And Scan Docker Image
    runs-on: ubuntu-latest

    steps:

      # ---------- Checkout ----------
      - name: Checkout Repo
        uses: actions/checkout@v4


      # ---------- Build ----------
      - name: Build Docker Image
        run: |
          docker build -t myapp:latest .


      # ---------- Security Scan ----------
      - name: Trivy Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: myapp:latest
          format: json
          output: trivy-report.json
          severity: HIGH,CRITICAL
          exit-code: 1


      # ---------- Upload Report ----------
      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.json


  push_image:
    name: Push Image To DockerHub
    needs: build_scan
    runs-on: ubuntu-latest

    steps:

      # ---------- Checkout ----------
      - name: Checkout Repo
        uses: actions/checkout@v4


      # ---------- Build Again ----------
      # (GitHub runners are isolated so we rebuild)
      - name: Build Docker Image
        run: |
          docker build -t myapp:latest .


      # ---------- Docker Login ----------
      - name: Login To DockerHub
        run: |
          echo "${{ secrets.DOCKER_PASS }}" | docker login \
          -u "${{ secrets.DOCKER_USER }}" \
          --password-stdin


      # ---------- Tag ----------
      - name: Tag Image
        run: |
          docker tag myapp:latest ${{ secrets.DOCKER_USER }}/myapp:ci


      # ---------- Push ----------
      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKER_USER }}/myapp:ci
